// Generated by scripts/sync-version.ts.

/** Current mppx package version. */
export const version = '0.9.2'

/** Canonical identifier for this mppx release. */
export const userAgent = `mppx/${version}`
