import fs from 'node:fs'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')) as {
  version: string
}
if (!/^[0-9A-Za-z.+-]+$/.test(packageJson.version))
  throw new Error(`Invalid package version: ${packageJson.version}`)

const content = `// Generated by scripts/sync-version.ts.

/** Current mppx package version. */
export const version = '${packageJson.version}'

/** Canonical identifier for this mppx release. */
export const userAgent = \`mppx/\${version}\`
`

fs.writeFileSync(path.join(root, 'src/internal/version.ts'), content)
